spring:
  application:
    name: msconfig
  cloud:
    config:
      server:
        git:
          uri: https://${CONFIG_GIT_URL:github.com/md-tareqaziz/Configurations}

server:
  port: ${CONFIG_PORT:9191}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_HOST:192.168.1.4}:${REGISTRY_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
#    hostname: ${REGISTRY_HOST:localhost}
