spring:
  application:
    name: msconfig
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URL:https://github.com/md-tareqaziz/Configurations}

server:
  port: ${CONFIG_PORT:9191}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${REGISTRY_SERVICE:http://192.168.1.4:8761/eureka/}
  instance:
    prefer-ip-address: true
#    hostname: ${REGISTRY_HOST:localhost}
