spring:
  application:
    name: msconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/md-tareqaziz/Configurations

server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${REGISTRY_SERVICE:192.168.1.4:8761}/eureka/
  instance:
    prefer-ip-address: true
#    hostname: ${REGISTRY_HOST:localhost}
